### ISSUE TITLE
libnet80211.a compile Error

### ISSUE THREAD

**Issue by YanMinge** [espressif/esp32-wifi-lib#12]
I followed the two issue on esp-idf
https://github.com/espressif/esp-idf/issues/1099
https://github.com/espressif/esp-idf/issues/1151
 
and I see some sample code here 
https://github.com/SuperHouse/esp-open-rtos/blob/master/open_esplibs/libnet80211/wl_cnx.c

but I don't konw why wl_cnx.c 's function  `cnx_do_handoff ` need call `wpa2_machine_star` and  `wps_start` and why it error here.

**Comment by projectgus** [comment]
Please use the first linked issue (1099) to discuss this, rather than continuing to open duplicate issues.

The linked sample code is reverse engineered from an old version of the ESP8266 libraries. It doesn't apply here.
