### ISSUE TITLE
FTM sessions are rate-limited

### ISSUE THREAD

**Issue by crackwitz** [espressif/esp32-wifi-lib#26]
When running the `ftm` example (on ESP32-S2) and requesting `ftm -I -s ...` repeatedly, eventually the request fails forever with status 2 (`FTM_STATUS_CONF_REJECTED` presumably). The softAP still responds to any other clients, unless they too exceed the rate limit.

I would prefer to run measurements as fast and as often as possible and get every available piece of information (thesis work). However, even when limiting the requests to one per 5.0 seconds, after a few minutes of requests, the AP seems to "ban" that client. Only resetting the AP allows that client to continue FTM sessions.

I would like to remove that rate limit. What can be done?

**Comment by wqiu-calgary** [comment]
is there any timeline to resolve this issue?

**Comment by crackwitz** [comment]
I don't think anyone at Espressif looks at the issues created on this repository. Other reported issues have stayed untouched for years.

**Comment by crackwitz** [comment]
Resolved with https://github.com/espressif/esp-idf/commit/c3d971c52e34ff7d6954a83e72155eabdc7e84cd
